services:
  votacao:
    container_name: votacao
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/votacao
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_FILTER_COMMONS_REQUEST_LOGGING_FILTER: DEBUG
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=votacao'
      - 'POSTGRES_PASSWORD=senha'
      - 'POSTGRES_USER=usuario'
    ports:
      - '5432:5432'