services:
  votacao:
    container_name: votacao
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbit
      - redis
    environment:
      RABBITMQ_USER: guest2
      RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/votacao
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_FILTER_COMMONS_REQUEST_LOGGING_FILTER: DEBUG

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=votacao'
      - 'POSTGRES_PASSWORD=senha'
      - 'POSTGRES_USER=usuario'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
#    command: [
#      "bash", "-c",
#      '
#       docker-entrypoint.sh
#       --requirepass password
#      '
#    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit:
    image: rabbitmq:3.7-management
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "15673:15672"
      - "5672:5672"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q status"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_PLUGINS: "rabbitmq_management, rabbitmq_delayed_message_exchange"