CREATE TABLE PAUTA (
    ID BIGINT NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    VOTOS_SIM INT NULL,
    VOTOS_NAO INT NULL,
    INICIO_VOTACAO timestamp NULL,
    FIM_VOTACAO timestamp NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE PAUTA_SEQ START WITH 1 INCREMENT BY 1;